# Topico de recebimento das imagens 
camera_topic: /zedm/zed_node/left/image_rect_color


# Topico de publicar as bouding boxes
bouding_box_topic: /yolov5_ros2/bounding_boxes


# Habilitar janela de visualizacao
visualization_detection: true